"""
Owner: Neerav
Stretch goal: trains a small RandomForestRegressor to replace the
threshold-based health score with a learned one, using only synthetic data
generated by this script (no external dataset).

This is a standalone offline script - it is NOT imported by the running
app and does NOT touch synthetic_sensors.py's live per-process state (that
module's in-memory readings belong to the running API, not a training
corpus). It re-derives its own synthetic trajectories over a seeded RNG,
using wider baseline/drift ranges than the live 5-machine demo so the
model generalizes a bit beyond exactly those 5 machines.

Run manually:
    python -m app.model.train
"""
import os
import random

from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.model_selection import train_test_split

from app.model.health_score import FEATURES, MODEL_WEIGHTS_PATH, _rule_based_score

N_MACHINES = 200
TICKS_PER_MACHINE = 60
DEGRADING_FRACTION = 0.4
SEED = 42


def _simulate_machine(rng: random.Random, degrading: bool) -> list:
    baseline_vibration = rng.uniform(1.8, 2.8)
    baseline_temperature = rng.uniform(50.0, 65.0)
    drift_mult = rng.uniform(0.5, 1.8)

    vibration = baseline_vibration
    temperature = baseline_temperature

    readings = []
    for _ in range(TICKS_PER_MACHINE):
        if degrading:
            vibration += 0.06 * drift_mult + rng.gauss(0, 0.05)
            temperature += 0.35 * drift_mult + rng.gauss(0, 0.3)
        else:
            k = 0.3
            vibration += k * (baseline_vibration - vibration) + rng.gauss(0, 0.08)
            temperature += k * (baseline_temperature - temperature) + rng.gauss(0, 0.4)

        readings.append({
            "vibration": round(vibration, 2),
            "temperature": round(temperature, 1),
            "rpm": rng.randint(1450, 1550),
        })
    return readings


def generate_dataset(seed: int = SEED) -> list:
    rng = random.Random(seed)
    rows = []
    for _ in range(N_MACHINES):
        degrading = rng.random() < DEGRADING_FRACTION
        rows.extend(_simulate_machine(rng, degrading))
    return rows


def main():
    data = generate_dataset()
    X = [[r[f] for f in FEATURES] for r in data]
    y = [_rule_based_score(r) for r in data]

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=SEED
    )

    model = RandomForestRegressor(
        n_estimators=60, max_depth=6, random_state=SEED, n_jobs=-1
    )
    model.fit(X_train, y_train)

    train_r2 = model.score(X_train, y_train)
    test_r2 = model.score(X_test, y_test)
    test_mae = mean_absolute_error(y_test, model.predict(X_test))
    print(f"train R^2={train_r2:.4f}  test R^2={test_r2:.4f}  test MAE={test_mae:.3f}")
    print(f"feature_importances_ ({FEATURES}): {model.feature_importances_}")

    os.makedirs(os.path.dirname(MODEL_WEIGHTS_PATH), exist_ok=True)
    import joblib
    joblib.dump(model, MODEL_WEIGHTS_PATH)
    print(f"saved model to {MODEL_WEIGHTS_PATH}")


if __name__ == "__main__":
    main()
